# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-05 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('field_type', models.CharField(choices=[('char', 'Text'), ('integer', 'Integer'), ('date', 'Date'), ('select', 'Select Single')], default='char', max_length=10, verbose_name='Field Type')),
                ('required', models.BooleanField(default=True, help_text='Is value for this field required?', verbose_name='Required')),
                ('help_text', models.CharField(blank=True, default='', help_text='The help text appears below the field on the form.Use it to clarify what this field means or to give further instructions.', max_length=255, verbose_name='Help Text')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Risk Field',
                'verbose_name_plural': 'Risk Fields',
            },
        ),
        migrations.CreateModel(
            name='RiskFieldOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('risk_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='risks.RiskField')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Risk Field Option',
                'verbose_name_plural': 'Risk Field Options',
            },
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Risk Type',
                'verbose_name_plural': 'Risk Types',
            },
        ),
        migrations.AddField(
            model_name='riskfield',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='risks.RiskType'),
        ),
        migrations.AlterUniqueTogether(
            name='riskfieldoption',
            unique_together=set([('risk_field', 'value')]),
        ),
    ]
